### ISSUE TITLE
Diagram with integer numbers returns 'nan' values.

### ISSUE THREAD

**Issue by muszyna25** [scikit-tda/persim#3]
Example:

This does not work: dgm = [[0, 2], [0, 6], [0, 8]];

This one works fine: dgm = [[0.0, 2.0], [0.0, 6.0], [0.0, 8.0]];

Thanks for solving the issue!

**Comment by sauln** [comment]
Thanks for bringing this to my attention. I'll try to issue a fix this weekend.

**Comment by rannbaron** [comment]
This does look to me like a Python2 vs 3 issue, as Python3 essentially gets around the need to cast integers to floats. If @muszyna25 can confirm they are using Python2, I can try to figure out a workaround.

**Comment by sauln** [comment]
That would be really helpful.  I set up TravisCI with a test that is currently failing for their example on 2.7, but passing on 3.4+.  It looks like there is another failing test, probably from sloppy integer handling.

If you could figure something out, a PR would be greatly appreciated! Thanks!
