### ISSUE TITLE
Add tag for v0.1.2

### ISSUE THREAD

**Issue by williamjameshandley** [scikit-tda/persim#31]
Could you add a GitHub release for v0.1.2? This will make it easier to keep the [aur](https://aur.archlinux.org/packages/python-persim/) repository up to date

**Comment by sauln** [comment]
Woah, that's awesome! Are you maintaining that repo?

Should be good to go now.

**Comment by williamjameshandley** [comment]
Many thanks @sauln. Maintaining an aur repo isn't a large task (particularly for python packages with pip install). This one was needed as a dependency for [ripser](https://github.com/scikit-tda/ripser.py).
