### ISSUE TITLE
Persistence image for H0?

### ISSUE THREAD

**Issue by shiqingzhangCSU** [scikit-tda/persim#38]
I want to generate a persistent image for H0，but the value in persimage always is nan.This makes me confuse.Can you give an example? 
thanks！

**Comment by ctralie** [comment]
Hello, thank you for your interest in our library!  I think what's probably going on here is that in H0, there will always be at least one point in the persistence diagram with an infinite death time, and that's throwing everything off.  Here's how you might get rid of an infinite point (@sauln, we should probably add some default behavior around this in this library, possibly with a warning)

```
from ripser import ripser
import numpy as np
np.random.seed(0)
X = np.random.randn(1000, 3)  
dgm = ripser(X, maxdim=0)['dgms'][0]
dgm = dgm[np.isfinite(dgm[:, 1]), :]
```

Let me know if this fixes the issue
```

**Comment by shiqingzhangCSU** [comment]
Thank you！I have solved this problem！In fact, similar problems occurred when I calculated the distance of the wasserstein of H0.

**Comment by ctralie** [comment]
Glad it helped! Yeah that makes sense. I'll keep this issue open because
you're not the only one to get confused by this. We'll try to come up with
a better solution

**Comment by sauln** [comment]
Thanks @ctralie, I remember I've even been hung up on this one before. Warnings or a parameter to filter infs would be a great addition.
