### ISSUE TITLE
Error Code when using transform() for persim.Persimage

### ISSUE THREAD

**Issue by AmberWho** [scikit-tda/persim#39]
ripser behaves normally, but this happens even when I am copying and paste the sample codes in the [User Guide](https://persim.scikit-tda.org/notebooks/Persistence%20Images.html). Here's the error code for the user guide codes:

```
Traceback (most recent call last):

  File "F:\HolyCross\Works\2020SUMMER\TDA\D0\untitled0.py", line 43, in <module>
    img = pim.transform(dgms[1])

  File "C:\Users\ThinkPad\anaconda3\lib\site-packages\persim\images.py", line 94, in transform
    dgs = [np.copy(diagram, np.float64) for diagram in diagrams]

  File "C:\Users\ThinkPad\anaconda3\lib\site-packages\persim\images.py", line 94, in <listcomp>
    dgs = [np.copy(diagram, np.float64) for diagram in diagrams]

  File "<__array_function__ internals>", line 6, in copy

  File "C:\Users\ThinkPad\anaconda3\lib\site-packages\numpy\lib\function_base.py", line 775, in copy
    return array(a, order=order, copy=True)

ValueError: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
```

I am new in Python, may I know how I can solve this problem?

**Comment by sauln** [comment]
Hi, sorry this should be working on `master` branch right now. Could you try installing from source?

**Comment by AmberWho** [comment]
I apologize for this but I am not familiar with the process. Shall I uninstall the package and then reinstall it from source?

**Comment by AmberWho** [comment]
> Hi, sorry this should be working on `master` branch right now. Could you try installing from source?

I apologize for this but I am not familiar with the process. Shall I uninstall the package and then reinstall it from source?

**Comment by sauln** [comment]
Something like that.. I believe something like 
```
conda remove persim
git clone https://github.com/scikit-tda/persim.git
cd persim
conda install .
```

I'm not very familiar with Conda, but I think that should work.

**Comment by ctralie** [comment]
If you installed it with pip, you can also try

    pip uninstall persim
    git clone https://github.com/scikit-tda/persim.git
    cd persim
    python setup.py install

**Comment by AmberWho** [comment]
Thank you very much! I uninstalled conda also and it's solved now.
