### ISSUE TITLE
Bottleneck distance between repeated intervals = 0

### ISSUE THREAD

**Issue by winsy17** [scikit-tda/persim#44]
The code below should produce a bottleneck distance of 0.5, but it outputs 0. 
Any number of repeated intervals (but different between G and H) has the same issue.

import numpy as np
import persim
G= np.array([[ 0,  1], [0,1]])
H= np.array([[ 0,  1]])
print(persim.bottleneck(G, H))

**Comment by ctralie** [comment]
Thank you so much for bringing this to our attention.  I will try to figure
out what's going on as soon as I can, though I am in a crunch with remote
teaching at the moment.

In the meantime, you may want to check out hera:
https://bitbucket.org/grey_narn/geom_bottleneck/src/master/

Best,
Chris

**Comment by ctralie** [comment]
Hey, you probably moved on from this a while ago, but my pandemic teaching is finally done, and I fixed this.  I'll push an official package later tonight, and you can let me know if you're still having any issues
