### ISSUE TITLE
Gaussian mean parameters in PersistenceImager

### ISSUE THREAD

**Issue by davafe** [scikit-tda/persim#56]
What is the value of mean parameter used if we use a gaussian kernel ? The gaussian kernel corresponding to a point of the diagram is centered in that point of the diagram?

**Comment by catanzaromj** [comment]
The gaussian is centered at each point in the diagram with variance 1. See https://github.com/scikit-tda/persim/blob/f58729c95b18c05782bc4ae8c458bdbfe2e88184/persim/images_kernels.py#L44-L47
