### ISSUE TITLE
persistent landscape

### ISSUE THREAD

**Issue by waqarshah786** [scikit-tda/persim#59]
anybody...!!!
Why persistent landscape module is not working in persim?

**Comment by catanzaromj** [comment]
Hi @waqarshah786. Can you please include some code or a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) that led you to the error?

**Comment by waqarshah786** [comment]
@catanzaromj its works with this command
from persim.landscapes import PersLandscapeExact
persim.landscapes.plot_landscape_simple(persim.landscapes.PersLandscapeExact(dgms_torus, hom_deg=1),title="Degree 1 Persistence Landscape of Torus", ax=axs[0])

please update these commands on persim as well. Thanks
