### ISSUE TITLE
PersistenceImager error

### ISSUE THREAD

**Issue by stauntonjr** [scikit-tda/persim#60]
I'm getting the following traceback, I think there was a change in the standard library https://docs.python.org/3/library/collections.abc.html 
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/36486177/192008212-a49bfd5b-0ff3-4a2b-bb92-bbb3b96ffc1c.png">
necessitating a small change to the source code on line 618

I am using py 3.10

Thanks

**Comment by curieux** [comment]
This should be simple to fix:
`collections.Iterable` is a typo.  It should be `typing.Iterable`

**Comment by curieux** [comment]
Alternately, see https://github.com/scikit-tda/persim/pull/58

**Comment by catanzaromj** [comment]
@stauntonjr This should be fixed in the newly-released persim v0.3.2. If the issue persists, please re-open.
