### ISSUE TITLE
Sorry, but I really to know what function this line of code do

### ISSUE THREAD

**Issue by h505023992** [scikit-tda/persim#61]
Sorry, but I really want to understand what this code do
`curr_img[1:, 1:] - curr_img[:-1, 1:] - curr_img[1:, :-1] + curr_img[:-1, :-1]`
in persim/images.py _transform
`pers_img += wts[i]*(curr_img[1:, 1:] - curr_img[:-1, 1:] - curr_img[1:, :-1] + curr_img[:-1, :-1])`

**Comment by ctralie** [comment]
This implements an integral image:
https://computersciencesource.wordpress.com/2010/09/03/computer-vision-the-integral-image/
