### ISSUE TITLE
Persistence Image for H0, H1, and H2 plus dropping inf values

### ISSUE THREAD

**Issue by tydymy** [scikit-tda/persim#63]
Hello, 

I am running 

pimgr = PersistenceImager(pixel_size=size,kernel_params={'sigma': [[1.0, 0.0], [0.0, 1.0]]})
pimgr.fit(diagrams_h1)

I was wondering if it possible to 1) drop features that extend to inf using flags in PersistenceImager or in Rips to avoid the "OverflowError: cannot convert float infinity to integer" error when calling pimgr.fit().

and 2) is it possible to compute the PersistenceImage using more than one level of homology(i.e. H0, H1, H2 rather than just H1 from the documentation example). 

Thanks!

**Comment by catanzaromj** [comment]
If you have more questions about this, feel free to open another issue.
