### ISSUE TITLE
`=perism-0.2.0` multiple tests fail

### ISSUE THREAD

**Issue by TheChymera** [scikit-tda/persim#65]
This is the full [build log](https://ppb.chymera.eu/e85eb6.log) and the failing tests appear to be a superset of the test [failures reported for `=perism-0.1.3`](https://github.com/scikit-tda/persim/issues/64).

**Comment by catanzaromj** [comment]
@TheChymera This should be fixed in persim v0.3.2, which was released. If the issue remains, please re-open.
