### ISSUE TITLE
`=persim-0.3.0` 13 tests fail (`AttributeError` and `ValueError`)

### ISSUE THREAD

**Issue by TheChymera** [scikit-tda/persim#66]
Full build log seen [here](https://ppb.chymera.eu/7e19b3.log), this is a superset of the [failures reported for `=perism-0.2.0`](https://github.com/scikit-tda/persim/issues/65).

**Comment by TheChymera** [comment]
The same issues affect `=persim-0.3.1`.

**Comment by catanzaromj** [comment]
@TheChymera This should be fixed in persim v.0.3.2. If the issue remains, please re-open.
