### ISSUE TITLE
Bug Report: `persim.bottleneck` returns 0 for distinct diagrams

### ISSUE THREAD

**Issue by alperenkaran** [scikit-tda/persim#70]
**Description:**

The `persim.bottleneck` function returns an incorrect result for some input persistence diagrams. When using `dgm1 = np.array([[0, 10]])` and `dgm2 = np.array([[5, 5]])`, the function incorrectly evaluates and returns 0, which is inconsistent with the expected behavior.

**Environment:**
Python version: 3.9.13
Persim version: 0.3.1

**Comment by ctralie** [comment]
That is strange, thank you for bringing this up!

**Comment by catanzaromj** [comment]
@alperenkaran This specific bug should be fixed in v0.3.4. Let us know if you have any more questions. Thanks for finding this!
