### ISSUE TITLE
How to calculate the distance between two landscapes?

### ISSUE THREAD

**Issue by HeJiaxing-hjx** [scikit-tda/persim#71]
I averaged different categories of persistent landscapes. How can I calculate the distance between a certain landscape with this average landscape? I want to use it to classify.

**Comment by catanzaromj** [comment]
@hejx1996 `persim` provides p-norm methods for landscapes, and you can use these to compute distances with the familiar formula `d(x,y) = ||x-y||`. So I would take the distance between the certain landscape and your average landscape, and then take its p-norm (for whatever p you'd like). 

If you have another distance function in mind, you can certainly implement it yourself using either the critical pairs (for exact landscapes) or for sampled values (for approximate landscapes).

**Comment by HeJiaxing-hjx** [comment]
> @hejx1996 `persim` provides p-norm methods for landscapes, and you can use these to compute distances with the familiar formula `d(x,y) = ||x-y||`. So I would take the difference between the certain landscape and your average landscape, and then take its p-norm (for whatever p you'd like).
> 
> If you have another distance function in mind, you can certainly implement it yourself using either the critical pairs (for exact landscapes) or for sampled values (for approximate landscapes).

I understand, thank you.
