### ISSUE TITLE
bring CI pipeline up to Python 3.12

### ISSUE THREAD

**Issue by curieux** [scikit-tda/persim#72]
The existing CI test pipeline stops at Python 3.8, and versions prior to 3.6 are not even included in Github's docker images anymore.

This issue is to bring the CI pipeline up to date to 3.12, which will facilitate the work in this milestone.

This issue blocks the other issues in that milestone.

**Comment by catanzaromj** [comment]
This was fixed with https://github.com/scikit-tda/persim/pull/73
