### ISSUE TITLE
Global rcParams change on import

### ISSUE THREAD

**Issue by OnDraganov** [scikit-tda/persim#81]
In `persim/landscapes/visuals.py`, line 15 defines `mpl.rcParams["text.usetex"] = True`. This means that whenever we import `persim`, the behavior of `pyplot` changes to that setting in all the `pyplot` uses. This is undesirable, as the user might prefer the default `pyplot` options for other uses than calls through `persim`.

If TeX rendering is necessary for the plots, is it possible to do the change only locally whenever a plot is created? It could be done using `with mpl.rc_context({"text.usetex": True}):` construction or by passing `usetex=True` at the individual places where it is desired.

**Comment by catanzaromj** [comment]
Thanks for the issue @OnDraganov. Absolutely! I agree that this shouldn't be set as a global. I believe we only use TeX for subscripts and superscripts in a mathematician friendly way. I think the context manager `mpl.rc_context` is a great way to deal with this. Are you interested in submitting a PR to implement the change?

**Comment by maximelucas** [comment]
I've just encountered the same problem. 

If TeX is only used for subscripts and superscripts, it might not be necessary at all? 
Default math rendering by matplotlib does this already. In that case, I would remove the line entirely and let the user choose to turn TeX if they want to.

Unless you use specific characters with which it may not work?

**Comment by catanzaromj** [comment]
@maximelucas The layers of the landscapes (indexed over `depth`) are typically denoted with $\lambda$, but I don't think we need latex for that. I think we can just use unicode characters, as shown in the updated answer [here](https://stackoverflow.com/a/13338569). If you agree, then please submit a PR implementing that change.

**Comment by OnDraganov** [comment]
I tried and r$\lambda_{2}$ actually shows correctly even with `matplotlib.rcParams['text.usetex']` being `False` (matplotlib version 3.8.4). So just erasing the 15 should be enough. Is that worth a pull request?

**Comment by maximelucas** [comment]
Yes most of the time it works even without the "r" in front.
I just created a PR.
